import pandas as pd

# Define the mapping of names between datasets
name_mapping = {
    'Adygea': 'Adygey',
    'Altai Krai': 'Altay',
    'Altai Republic': 'Gorno-Altay',
    'Amur Oblast': 'Amur',
    'Arkhangelsk Oblast': 'Arkhangel\'sk',
    'Astrakhan Oblast': 'Astrakhan\'',
    'Bashkortostan': 'Bashkortostan',
    'Belgorod Oblast': 'Belgorod',
    'Bryansk Oblast': 'Bryansk',
    'Buryatia': 'Buryat',
    'Chechnya': 'Chechnya',
    'Chelyabinsk Oblast': 'Chelyabinsk',
    'Chukotka Autonomous Okrug': 'Chukchi Autonomous Okrug',
    'Chuvashia': 'Chuvash',
    'Dagestan': 'Dagestan',
    'Ingushetia': 'Ingush',
    'Irkutsk Oblast': 'Irkutsk',
    'Ivanovo Oblast': 'Ivanovo',
    'Jewish Autonomous Oblast': 'Yevrey',
    'Kabardino-Balkaria': 'Kabardin-Balkar',
    'Kaliningrad Oblast': 'Kaliningrad',
    'Kalmykia': 'Kalmyk',
    'Kaluga Oblast': 'Kaluga',
    'Kamchatka Krai': 'Kamchatka',
    'Karachay-Cherkessia': 'Karachay-Cherkess',
    'Karelia': 'Karelia',
    'Kemerovo Oblast': 'Kemerovo',
    'Khabarovsk Krai': 'Khabarovsk',
    'Khakassia': 'Khakass',
    'Khanty-Mansi Autonomous Okrug': 'Khanty-Mansiy',
    'Kirov Oblast': 'Kirov',
    'Komi Republic': 'Komi',
    'Kostroma Oblast': 'Kostroma',
    'Krasnodar Krai': 'Krasnodar',
    'Krasnoyarsk Krai': 'Krasnoyarsk',
    'Kurgan Oblast': 'Kurgan',
    'Kursk Oblast': 'Kursk',
    'Leningrad Oblast': 'Leningrad',
    'Lipetsk Oblast': 'Lipetsk',
    'Magadan Oblast': 'Maga Buryatdan',
    'Mari El': 'Mariy-El',
    'Mordovia': 'Mordovia',
    'Moscow': 'Moskva',
    'Moscow Oblast': 'Moskovskaya',
    'Murmansk Oblast': 'Murmansk',
    'Nenets Autonomous Okrug': 'Nenets',
    'Nizhny Novgorod Oblast': 'Nizhegorod',
    'North Ossetia–Alania': 'North Ossetia',
    'Novgorod Oblast': 'Novgorod',
    'Novosibirsk Oblast': 'Novosibirsk',
    'Omsk Oblast': 'Omsk',
    'Orenburg Oblast': 'Orenburg',
    'Penza Oblast': 'Penza',
    'Perm Krai': 'Perm\'',
    'Primorsky Krai': 'Primor\'ye',
    'Pskov Oblast': 'Pskov',
    'Republic of Crimea': 'Republic of Crimea',
    'Rostov Oblast': 'Rostov',
    'Russian Federation': 'Russian Federation',
    'Ryazan Oblast': 'Ryazan\'',
    'Saint Petersburg': 'City of St. Petersburg',
    'Sakha Republic': 'Sakha (Yakutia)',
    'Sakhalin Oblast': 'Sakhalin',
    'Samara Oblast': 'Samara',
    'Saratov Oblast': 'Saratov',
    'Sevastopol': 'Sevastopol',
    'Smolensk Oblast': 'Smolensk',
    'Stavropol Krai': 'Stavropol\'',
    'Sverdlovsk Oblast': 'Sverdlovsk',
    'Tambov Oblast': 'Tambov',
    'Tatarstan': 'Tatarstan',
    'Tomsk Oblast': 'Tomsk',
    'Tula Oblast': 'Tula',
    'Tuva': 'Tuva',
    'Tver Oblast': 'Tver\'',
    'Tyumen Oblast': 'Tyumen\'',
    'Udmurtia': 'Udmurt',
    'Ulyanovsk Oblast': 'Ul\'yanovsk',
    'Vladimir Oblast': 'Vladimir',
    'Volgograd Oblast': 'Volgograd',
    'Vologda Oblast': 'Vologda',
    'Voronezh Oblast': 'Voronezh',
    'Yamalo-Nenets Autonomous Okrug': 'Yamal-Nenets',
    'Yaroslavl Oblast': 'Yaroslavl',
    'Zabaykalsky Krai': 'Chita'
}

# Load the CSV data from the URL
url = 'https://raw.githubusercontent.com/rhysw-h/rhysw-h.github.io/refs/heads/main/russian_grdp.csv'
df = pd.read_csv(url)

# Rename the regions in the dataframe
df['Federal subject'] = df['Federal subject'].replace(name_mapping)

# Save the updated dataframe to a new CSV
df.to_csv('updated_russian_grdp.csv', index=False)

